### ISSUE TITLE
publish to maven central

### ISSUE THREAD

**Issue by physikerwelt** [alexeygrigorev/rseq#1]

**Comment by alexeygrigorev** [comment]
- guide for publishing to sonatype nexus: http://central.sonatype.org/pages/ossrh-guide.html and http://central.sonatype.org/pages/apache-maven.html
- project ticket: https://issues.sonatype.org/browse/OSSRH-18043

**Comment by alexeygrigorev** [comment]
rseq is now deployed to Sonatype's snapshot repository: https://oss.sonatype.org/content/repositories/snapshots/com/alexeygrigorev/rseq/0.0.1-SNAPSHOT/

But before releasing to the release repository (which will propagate to maven central) I need to complete the java docs and finish some documentation.

Now you can use it from maven by adding the sonatype snapshot repository:

    <project>
    ...
      <repositories>
        <repository>
          <id>sonatype-shapshot</id>
          <name>Sonatype Snapshot Repository</name>
          <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
      </repositories>
      <dependencies>
        <dependency>
          <groupId>com.alexeygrigorev</groupId>
          <artifactId>rseq</artifactId>
          <version>0.0.1-SNAPSHOT</version>
        </dependency>
        ...
      </dependencies>

    </project>

**Comment by physikerwelt** [comment]
... However, you should never use dependencies to -SNAPSHOT versions... maven is not very convinent if the conent of the snapshot version changes

**Comment by alexeygrigorev** [comment]
just use the `-U` key - then it will update the snapshots

**Comment by alexeygrigorev** [comment]
The library is published to maven central: http://central.maven.org/maven2/com/alexeygrigorev/rseq/0.0.1/

You can use this snippet:

    <dependency>
      <groupId>com.alexeygrigorev</groupId>
      <artifactId>rseq</artifactId>
      <version>0.0.1</version>
    </dependency>
